# Generated by Django 5.0.9 on 2024-11-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, default='A celebration of food', max_length=100),
            preserve_default=False,
        ),
    ]
